apiVersion: v1
kind: Service
metadata: # Metadata for the service
  name: mongo
  labels:
    app: mongo
spec:
  type: ClusterIP # Service type
  selector: # Selector to match pods
    app: mongo
  ports: # Port configuration
    - protocol: TCP
      port: 27017 #t exposed by the service
      targetPort: 27017 # Port on the pod to forward traffic to
      